### PR TITLE
Further updates to icons

### PR DESCRIPTION
**Pull request by unknowndomain**

### CODE REVIEW

**Comment by erinzm** [comment]
Ooh, nice! Since you've already put in all that work, don't bother redoing it with flat icons, it's _amazing_ the way it is.

**Comment by unknowndomain** [comment]
I would just like to see the icon used. I spent time doing it a few years ago and it would be good for it to find a new use... Last icon I did like this is still used in an iOS app... it's fun to see it in use!

**Comment by erinzm** [comment]
If you could put the source files (PSDs or whatever) in src/main/resources/sources, that would be great, in case anything needs to be changed later on.

**Comment by unknowndomain** [comment]
Sure.

**Comment by unknowndomain** [comment]
There we go, new icons and source files.

**Comment by unknowndomain** [comment]
You'll obviously need to test them when it is building again.

**Comment by erinzm** [comment]
Thank you _so_ much for contributing, I could never create an icon like that. Yay for open source!

**Comment by unknowndomain** [comment]
:smile: let me know if you need any other tinkerings.

**Comment by erinzm** [comment]
@unknowndomain: I finally got the build working with Gradle (which is great), and this is what the icon looks like in my taskbar: the icon looks awesome
Thanks again :smile:

**Comment by unknowndomain** [comment]
Thats still the gradient icon? What happened?

**Comment by erinzm** [comment]
The buildscript's looking in the wrong place for the icon.

**Comment by unknowndomain** [comment]
Aye, but where is there a gradient icon in the first place? I replaced them all, I thought.

**Comment by erinzm** [comment]
Oh, wait, I just remembered that Ubuntu Unity _does_ gently gradient towards the bottom, it is using the flat one.

**Comment by unknowndomain** [comment]
Ha!

**Pull request merged**
